// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';
import { HelmetProvider } from '/Users/jiangxue/FrontEnd/Pubrio/Weather-Test/node_modules/.pnpm/registry.npmjs.org+@umijs+renderer-react@4.2.9_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react';
import { context } from './helmetContext';

export const innerProvider = (container) => {
  return React.createElement(HelmetProvider, { context }, container);
}
