// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import routeProps from './routeProps';

if (process.env.NODE_ENV === 'development') {
  Object.entries(routeProps).forEach(([key, value]) => {
    const internalProps = ['path', 'id', 'parentId', 'isLayout', 'isWrapper', 'layout', 'clientLoader'];
    Object.keys(value).forEach((prop) => {
      if (internalProps.includes(prop)) {
        throw new Error(
          `[UmiJS] route '${key}' should not have '${prop}' prop, please remove this property in 'routeProps'.`
        )
      }
    })
  })
}

import React from 'react';

export async function getRoutes() {
  const routes = {"panel/historyItem":{"path":"panel/historyItem","id":"panel/historyItem","parentId":"@@/global-layout"},"search/search":{"path":"search/search","id":"search/search","parentId":"@@/global-layout"},"panel/index":{"path":"panel","id":"panel/index","parentId":"@@/global-layout"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'panel/historyItem': React.lazy(() => import(/* webpackChunkName: "src__pages__panel__historyItem" */'../../../src/pages/panel/historyItem.jsx')),
'search/search': React.lazy(() => import(/* webpackChunkName: "src__pages__search__search" */'../../../src/pages/search/search.jsx')),
'panel/index': React.lazy(() => import(/* webpackChunkName: "src__pages__panel__index" */'../../../src/pages/panel/index.jsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'/Users/jiangxue/FrontEnd/React-weatherTest/src/layouts/index.jsx')),
},
  };
}
