// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// plugins
export { Icon } from '/Users/jiangxue/FrontEnd/React-weatherTest/src/.umi/plugin-icons';
// plugins types.d.ts
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from '/Users/jiangxue/FrontEnd/React-weatherTest/node_modules/.pnpm/registry.npmjs.org+@umijs+renderer-react@4.2.9_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react';
export type { History } from '/Users/jiangxue/FrontEnd/React-weatherTest/node_modules/.pnpm/registry.npmjs.org+@umijs+renderer-react@4.2.9_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from '/Users/jiangxue/FrontEnd/React-weatherTest/node_modules/.pnpm/registry.npmjs.org+umi@4.2.9_@babel+core@7.24.6_eslint@8.57.0_prettier@3.3.0_react-dom@18.3.1_y2hz6tl5b7px5o76xirf6t6oxq/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
// react ssr
export const useServerInsertedHTML: Function = () => {};
// test
export { TestBrowser } from './testBrowser';
